### ISSUE TITLE
Completion of step "2.3 Startup Disk Creator"

### ISSUE THREAD

**Issue by Maribomba-Azure** [brendenyule/NativeToshibaCB2Guide#1]
Hi,

First thanks for all the great documentation.
Now I've got stuck at step "2.3 Startup Disk Creator" can you guide me in the right direction or what can I do to help you to have it all documented?

Thanks, Chris

**Comment by brendenyule** [comment]
Yeah, I can help you, let me know when you have time. We can IM on hangouts.

**Comment by Maribomba-Azure** [comment]
Sorry I don't do IM.

**Comment by brendenyule** [comment]
I'm not sure what else I could do to help you then. I can try my best, but there would be a lot of troubleshooting, and this probably wouldn't be the best medium for it.
