### ISSUE TITLE
A Slight Clarification May Improve This Guide

### ISSUE THREAD

**Issue by ddade** [brendenyule/NativeToshibaCB2Guide#4]
First, thank you so much for this guide. I've got 15.10 on a C670 and almost on my new i3 Toshiba Chromebook 2.

But a hiccup I ran into with the Toshiba was that the guide correctly illustrates that there is no heatshield to be removed, and the write protect screw simply needs to be removed. But the guide _doesn't_ say that after removing the screw, there is still that conductive ring around the screwhole that needs to removed, just like in the other steps for the non i3 version. My eyesight is not what it used to be, and I missed this ring without carefully looking for it. If you don't remove it, the circuit is still closed, and the "flashrom --wp-disable" will fail.

Other than that, the guide is absolutely perfect, and I thank you for it.

**Comment by brendenyule** [comment]
Did you take a picture of the sticker by chance?

**Comment by brendenyule** [comment]
Also as you have personal experience with the issue, feel free to modify the section yourself with the steps you took. Would definitely improve the guide.

**Comment by ddade** [comment]
You know, I didn't have the presence of mind to do that. But it sounded a
lot like the one for the non-i3 model... Just an adhesive ring of a
metallic-like substance that easily came off in one piece, using the tip of
an X-Acto knife.

**Comment by jcreek** [comment]
This is completely the wrong place to post this but I'd rather not make you a new issue. Has anyone tried installing Windows after this process? I know there's some work available here https://www.reddit.com/r/chromeos/comments/3gnema/tutorial_install_windows_10_on_the_acer_c720/?sort=new

**Comment by brendenyule** [comment]
Hijacking an issue is inappropriate jcreek, I am deleting your comment.

**Comment by brendenyule** [comment]
@ddade thanks for adding to the guide to clarify the process!

**Comment by ddade** [comment]
No problem, I really appreciate this guide... I now have 15.10 running on
my cb3-3350, thanks to you.

**Comment by brendenyule** [comment]
No problem, glad it helped you, hopefully it will help more people as well.
