### ISSUE TITLE
Avoid sudo with GUI tools

### ISSUE THREAD

**Issue by ghost** [brendenyule/NativeToshibaCB2Guide#5]
Using _sudo gedit_ early in an installation/configuration effort can make ~/.config/ owned by root, which will break other GUI tools.  This is a trivial issue for more experienced users, but completely sucks for anyone else.

Better to use **sudoedit file-to-be-edited**, which is always safe. The EDITOR environment variable is honored. nano is the default if available and unset.

sudoedit is a best practice for editing all system files on Linux.

**Comment by brendenyule** [comment]
Did you personally experience this issue? I don't understand how this could be a problem, you aren't using gedit until well after the install is complete.

**Comment by brendenyule** [comment]
Did you run the command yourself, at a time not specified by the guide?

**Comment by ghost** [comment]
http://www.wingtiplabs.com/blog/posts/2013/03/13/sudoedit/
Just trying to help make it better. There non-gnome installs which would be impacted by this. There are other issues with sudo gedit.

**Comment by brendenyule** [comment]
Actually in this case with the target users, chosen operating system, and general simplicity, I think that gedit is the correct choice. It doesn't have any negative impact, and is simple to use. 

I see your point for users of other distributions, and I think that an Arch or Debian user should already know how to use sudoedit, and should not be learning it here.

Feel free to add a note in the wiki if you feel it would help people.
